-- MySQL Script generated by MySQL Workbench
-- 11/05/14 22:25:47
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema roach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `roach` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `roach` ;

-- -----------------------------------------------------
-- Table `roach`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`role` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NULL,
  `parent_default_role` VARCHAR(45) NULL,
  `organisation_id` INT UNSIGNED NULL,
  `name` VARCHAR(45) NULL,
  `type` ENUM('global','organisation','project') NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_name` (`name` ASC),
  INDEX `role_fk_parent_id` USING BTREE (`parent_id` ASC),
  INDEX `role_fk_organisation_id` (`organisation_id` ASC),
  INDEX `role_fk_uoc_idx` (`uoc` ASC),
  INDEX `role_fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `role_fk_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `roach`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_fk_organisation_id`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `roach`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `default_role` VARCHAR(45) NULL,
  `role_id` INT UNSIGNED NULL,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `status` ENUM('active','inactive','blocked') NULL,
  `token` VARCHAR(100) NULL,
  `token_toc` DATETIME NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_email` (`email` ASC),
  INDEX `user_fk_role_id` (`role_id` ASC),
  INDEX `user_fk_uoc` (`uoc` ASC),
  INDEX `user_fk_uolu` (`uolu` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  CONSTRAINT `user_fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `roach`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`organisation` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `logo` VARCHAR(45) NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `organisation_fk_uolu` (`uolu` ASC),
  INDEX `organisation_fk_uoc` (`uoc` ASC),
  CONSTRAINT `organisation_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organisation_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`project` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NOT NULL,
  `organisation_id` INT UNSIGNED NULL,
  `workflow_id` INT UNSIGNED NULL,
  `type` ENUM('project','milestone') NULL,
  `name` VARCHAR(45) NULL,
  `initial` VARCHAR(10) NULL,
  `date_start` DATETIME NULL,
  `date_end` DATETIME NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_projects_organisations1_idx` (`organisation_id` ASC),
  INDEX `fk_projects_projects1_idx` (`parent_id` ASC),
  INDEX `fk_uoc_idx` (`uoc` ASC),
  INDEX `fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `project_fk_organisation_id`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `roach`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_fk_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `roach`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`workflow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`workflow` (
  `id` INT UNSIGNED NOT NULL,
  `organisation_id` INT UNSIGNED NULL,
  `name` VARCHAR(45) NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_work_flow_organisations1_idx` (`organisation_id` ASC),
  INDEX `fk_uoc_idx` (`uoc` ASC),
  INDEX `fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `workflow_fk_organisation_id`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `roach`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workflow_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workflow_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`workflow_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`workflow_status` (
  `id` INT UNSIGNED NOT NULL,
  `workflow_id` INT UNSIGNED NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_workflow_status_workflow1_idx` (`workflow_id` ASC),
  INDEX `fk_uoc_idx` (`uoc` ASC),
  INDEX `fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `workflow_status_fk_workflow_id`
    FOREIGN KEY (`workflow_id`)
    REFERENCES `roach`.`workflow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workflow_status_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workflow_status_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`task` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NULL,
  `project_id` INT UNSIGNED NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `priority` VARCHAR(45) NULL,
  `severity` VARCHAR(45) NULL,
  `workflow_status_id` INT UNSIGNED NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tasks_tasks1_idx` (`parent_id` ASC),
  INDEX `fk_tasks_projects1_idx` (`project_id` ASC),
  INDEX `fk_tasks_workflow_status1_idx` (`workflow_status_id` ASC),
  INDEX `fk_uoc_idx` (`uoc` ASC),
  INDEX `fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `task_fk_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `roach`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_fk_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `roach`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_fk_workflow_status_id`
    FOREIGN KEY (`workflow_status_id`)
    REFERENCES `roach`.`workflow_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`comment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NULL,
  `task_id` INT UNSIGNED NULL,
  `comment` TEXT NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `comment_fk_task_id` (`task_id` ASC),
  INDEX `comment_fk_uoc` (`uoc` ASC),
  INDEX `comment_fk_uolu` (`uolu` ASC),
  INDEX `fk_comment_parent_id1_idx` (`parent_id` ASC),
  CONSTRAINT `comment_fk_task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `roach`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_fk_parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `roach`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`attachment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` INT UNSIGNED NULL,
  `filename` TEXT NULL,
  `type` VARCHAR(10) NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `attachment_fk_task_id` (`task_id` ASC),
  INDEX `attachment_fk_uoc` (`uoc` ASC),
  CONSTRAINT `attachment_fk_task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `roach`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `attachment_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `roach`.`workflow_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`workflow_action` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `workflow_status_id_from` INT UNSIGNED NULL,
  `workflow_status_id_to` INT UNSIGNED NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_workflow_actions_workflow_status1_idx` (`workflow_status_id_from` ASC),
  INDEX `fk_workflow_actions_workflow_status2_idx` (`workflow_status_id_to` ASC),
  INDEX `fk_uoc_idx` (`uoc` ASC),
  INDEX `fk_uolu_idx` (`uolu` ASC),
  UNIQUE INDEX `uq_workflow_action` (`workflow_status_id_from` ASC, `workflow_status_id_to` ASC),
  CONSTRAINT `workflow_action_fk_workflow_status_id_from`
    FOREIGN KEY (`workflow_status_id_from`)
    REFERENCES `roach`.`workflow_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workflow_action_fk_workflow_status_id_to`
    FOREIGN KEY (`workflow_status_id_to`)
    REFERENCES `roach`.`workflow_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workflow_action_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `workflow_action_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`role_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT UNSIGNED NULL,
  `permission` VARCHAR(45) NULL,
  `access` ENUM('access','deny') NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `role_permission_fk_uoc_idx` (`uoc` ASC),
  INDEX `role_permission_fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `role_permission_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `role_permission_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`project_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`project_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NULL,
  `user_id` INT UNSIGNED NULL,
  `role_id` INT UNSIGNED NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_project_users_projects1_idx` (`project_id` ASC),
  INDEX `fk_project_users_users1_idx` (`user_id` ASC),
  INDEX `fk_project_users_roles1_idx` (`role_id` ASC),
  INDEX `fk_project_users_users1_idx1` (`uoc` ASC),
  INDEX `project_user_fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `project_user_fk_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `roach`.`project` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_user_fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_user_fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `roach`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_user_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_user_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`organisation_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`organisation_user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organisation_id` INT UNSIGNED NULL,
  `user_id` INT UNSIGNED NULL,
  `role_id` INT UNSIGNED NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `organisation_user_fk_organisation_id` (`organisation_id` ASC),
  INDEX `fk_user_id` (`user_id` ASC),
  INDEX `organisation_user_fk_role_id` (`role_id` ASC),
  UNIQUE INDEX `unique_organisation_user` (`organisation_id` ASC, `user_id` ASC),
  INDEX `organisation_user_fk_uoc_idx` (`uoc` ASC),
  INDEX `organisation_user_fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `organisation_user_fk_organisation_id`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `roach`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organisation_user_fk_user_if`
    FOREIGN KEY (`user_id`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organisation_user_fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `roach`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organisation_user_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organisation_user_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`organisation_user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`organisation_user_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `organisation_user_id` INT UNSIGNED NULL,
  `permission` VARCHAR(45) NULL,
  `access` ENUM('access','deny') NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `organisation_user_permission_fk_organisation_user_id` (`organisation_user_id` ASC),
  INDEX `organisation_user_permission_fk_uoc` (`uoc` ASC),
  INDEX `organisation_user_permission_fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `organisation_user_permission_fk_organisation_user_id`
    FOREIGN KEY (`organisation_user_id`)
    REFERENCES `roach`.`organisation_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organisation_user_permission_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `organisation_user_permission_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`project_user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`project_user_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_user_id` INT UNSIGNED NULL,
  `permission` VARCHAR(45) NULL,
  `access` ENUM('access','deny') NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `project_user_id_UNIQUE` (`project_user_id` ASC),
  UNIQUE INDEX `permission_UNIQUE` (`permission` ASC),
  INDEX `fk_projecct_user_permissions_users1_idx` (`uoc` ASC),
  INDEX `project_user_permission_fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `project_user_permission_fk_projecct_user_id`
    FOREIGN KEY (`project_user_id`)
    REFERENCES `roach`.`project_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_user_permission_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `project_user_permission_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`user_permission` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NULL,
  `permission` VARCHAR(45) NULL,
  `access` ENUM('allow','deny') NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `uolu` INT UNSIGNED NULL,
  `tolu` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `user_permission_fk_user_id` (`user_id` ASC),
  INDEX `user_permission_fk_uoc_idx` (`uoc` ASC),
  INDEX `user_permission_fk_uolu_idx` (`uolu` ASC),
  CONSTRAINT `user_permission_fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_permission_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_permission_fk_uolu`
    FOREIGN KEY (`uolu`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `roach`.`task_status_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `roach`.`task_status_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_id` INT UNSIGNED NULL,
  `workflow_status_id` INT UNSIGNED NULL,
  `uoc` INT UNSIGNED NULL,
  `toc` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_task_id_idx` (`task_id` ASC),
  INDEX `fk_workflow_status_id_idx` (`workflow_status_id` ASC),
  INDEX `fk_uoc_idx` (`uoc` ASC),
  CONSTRAINT `task_status_history_fk_task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `roach`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_status_history_fk_workflow_status_id`
    FOREIGN KEY (`workflow_status_id`)
    REFERENCES `roach`.`workflow_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_status_history_fk_uoc`
    FOREIGN KEY (`uoc`)
    REFERENCES `roach`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
